//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5477
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceDAL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceDAL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DAL.Resources.ResourceDAL", typeof(ResourceDAL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קובץ הגדרות של מפעיל {0} לא מכיל הגדרה עבור אשכולות שלו.
        /// </summary>
        internal static string ClusterDefWasNotFountForOperator {
            get {
                return ResourceManager.GetString("ClusterDefWasNotFountForOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הרצת סקריפט לעדכון ערים לאחר הקליטה.
        /// </summary>
        internal static string Exec_UpdateInfrastructureCity {
            get {
                return ResourceManager.GetString("Exec_UpdateInfrastructureCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הרצת סקריפט לעדכון צמתים לאחר הקליטה.
        /// </summary>
        internal static string Exec_UpdateInfrastructureJunction {
            get {
                return ResourceManager.GetString("Exec_UpdateInfrastructureJunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הרצת סקריפט לעדכון תחנות לאחר הקליטה.
        /// </summary>
        internal static string Exec_UpdateInfrastructureStation {
            get {
                return ResourceManager.GetString("Exec_UpdateInfrastructureStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הקליטה נכשלה בגלל שקיימים תחנות בקו תחנה שעוד לא נקלטו בתשתית. פנה למנהל המערכת.
        /// </summary>
        internal static string ForeinConstrantViolated {
            get {
                return ResourceManager.GetString("ForeinConstrantViolated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יצוא של ערים.
        /// </summary>
        internal static string MessageProgressCity {
            get {
                return ResourceManager.GetString("MessageProgressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יצוא של צמתים.
        /// </summary>
        internal static string MessageProgressJunction {
            get {
                return ResourceManager.GetString("MessageProgressJunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הכנת רשומות של קו מוקד לתהליך היצוא.
        /// </summary>
        internal static string MessageProgressRouteNodesBuild {
            get {
                return ResourceManager.GetString("MessageProgressRouteNodesBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שמירת רשומות של קו מוקד בבסיס הנתונים.
        /// </summary>
        internal static string MessageProgressRouteNodesSave {
            get {
                return ResourceManager.GetString("MessageProgressRouteNodesSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הכנת רשומות של קו תחנה לתהליך היצוא.
        /// </summary>
        internal static string MessageProgressRouteStopsBuild {
            get {
                return ResourceManager.GetString("MessageProgressRouteStopsBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שמירת רשומות של קו תחנה בבסיס הנתונים.
        /// </summary>
        internal static string MessageProgressRouteStopsSave {
            get {
                return ResourceManager.GetString("MessageProgressRouteStopsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הכנת רשומות של קוים לתהליך היצוא.
        /// </summary>
        internal static string MessageProgressRouteSystemBuild {
            get {
                return ResourceManager.GetString("MessageProgressRouteSystemBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שמירת רשומות של קוים בבסיס הנתונים.
        /// </summary>
        internal static string MessageProgressRouteSystemSave {
            get {
                return ResourceManager.GetString("MessageProgressRouteSystemSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יצוא של תחנות.
        /// </summary>
        internal static string MessageProgressStation {
            get {
                return ResourceManager.GetString("MessageProgressStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קבוצת התחשבנות.
        /// </summary>
        internal static string OperatorGroup {
            get {
                return ResourceManager.GetString("OperatorGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route System לא נמצא.
        /// </summary>
        internal static string RouteSystemUnloaded {
            get {
                return ResourceManager.GetString("RouteSystemUnloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תוכנת טרנסקד לא הופעלה.
        /// </summary>
        internal static string TranCadIsNotRunning {
            get {
                return ResourceManager.GetString("TranCadIsNotRunning", resourceCulture);
            }
        }
    }
}
