//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLEntities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BLEntities.Resources.ValidationResource", typeof(ValidationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קבוצת התחשבנות לא מוגדרת.
        /// </summary>
        internal static string AccountingGroupID_Type_Empty {
            get {
                return ResourceManager.GetString("AccountingGroupID_Type_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ב 56 לא מוגדר.
        /// </summary>
        internal static string B_56_Empty {
            get {
                return ResourceManager.GetString("B_56_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם אשכול לא מוגדר.
        /// </summary>
        internal static string Branch_Name_Empty {
            get {
                return ResourceManager.GetString("Branch_Name_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא הוגדרו רציף וקומה לתחנה.
        /// </summary>
        internal static string CentralStationFloorAndPlatformNotDefined {
            get {
                return ResourceManager.GetString("CentralStationFloorAndPlatformNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר אשכול לא מוגדר.
        /// </summary>
        internal static string Cluster_0 {
            get {
                return ResourceManager.GetString("Cluster_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם מפעיל לא מוגדר.
        /// </summary>
        internal static string Company_Empty {
            get {
                return ResourceManager.GetString("Company_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עדיין לא עבר תהליך ההמרה.
        /// </summary>
        internal static string ConvertWasNotCompleted {
            get {
                return ResourceManager.GetString("ConvertWasNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כיוון לא מוגדר.
        /// </summary>
        internal static string Dir_Empty {
            get {
                return ResourceManager.GetString("Dir_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עונתיות לא מוגדרת.
        /// </summary>
        internal static string ExclusivityLine_Type_Empty {
            get {
                return ResourceManager.GetString("ExclusivityLine_Type_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא מוגדרת תחנת הורדה.
        /// </summary>
        internal static string Horada_0 {
            get {
                return ResourceManager.GetString("Horada_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מזהה רשומה לא מוגדר.
        /// </summary>
        internal static string ID_0 {
            get {
                return ResourceManager.GetString("ID_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פעילות בתחנה לא מוגדר.
        /// </summary>
        internal static string IdStationType_0 {
            get {
                return ResourceManager.GetString("IdStationType_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude לא מוגד.
        /// </summary>
        internal static string Latitude_0 {
            get {
                return ResourceManager.GetString("Latitude_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ערך של שדה Longitude עבור הזזה לא מוגדר.
        /// </summary>
        internal static string Latitude_0_N {
            get {
                return ResourceManager.GetString("Latitude_0_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude לא מוגד.
        /// </summary>
        internal static string Longitude_0 {
            get {
                return ResourceManager.GetString("Longitude_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ערך של שדה Longitude עבור הזזה לא מוגדר.
        /// </summary>
        internal static string Longitude_0_N {
            get {
                return ResourceManager.GetString("Longitude_0_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחוז משנה לא מוגדר.
        /// </summary>
        internal static string Mahoz_Mishne_Empty {
            get {
                return ResourceManager.GetString("Mahoz_Mishne_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחוז ראשי לא מוגדר.
        /// </summary>
        internal static string Mahoz_Roshi_Empty {
            get {
                return ResourceManager.GetString("Mahoz_Roshi_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מקט לא יכול להיות 0.
        /// </summary>
        internal static string MAKAT_0 {
            get {
                return ResourceManager.GetString("MAKAT_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מקט לא מוגדר.
        /// </summary>
        internal static string MAKAT_Empty {
            get {
                return ResourceManager.GetString("MAKAT_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא הוגדר מרחק בין שני תחנות.
        /// </summary>
        internal static string Milepost_0 {
            get {
                return ResourceManager.GetString("Milepost_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם של ישות לא מוגדר.
        /// </summary>
        internal static string Name_Empty {
            get {
                return ResourceManager.GetString("Name_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר מפעיל לא מוגדר.
        /// </summary>
        internal static string Operator_0 {
            get {
                return ResourceManager.GetString("Operator_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא הוגדרה תחנה פיזית אליה שייכת תחנה בקו.
        /// </summary>
        internal static string Physical_Stop_ID_0 {
            get {
                return ResourceManager.GetString("Physical_Stop_ID_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תחנה לא נמצאת במאגר של תחנות.
        /// </summary>
        internal static string Physical_Stop_ID_Foreign_Not_Found {
            get {
                return ResourceManager.GetString("Physical_Stop_ID_Foreign_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כיוון של תחנה לא מוגדר נכון.
        /// </summary>
        internal static string PhysicalStop_Direction_NOT_IN_Domain {
            get {
                return ResourceManager.GetString("PhysicalStop_Direction_NOT_IN_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם תחנה לא מוגדר.
        /// </summary>
        internal static string PhysicalStop_Name_Empty {
            get {
                return ResourceManager.GetString("PhysicalStop_Name_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תיאור דרך לא מוגדר.
        /// </summary>
        internal static string RoadDescription_Empty {
            get {
                return ResourceManager.GetString("RoadDescription_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אורך של שדה חייב להיות לא יותר מי 20 תווים.
        /// </summary>
        internal static string RoadDescriptionLength {
            get {
                return ResourceManager.GetString("RoadDescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא מוגדר קו ששייך לתחנה.
        /// </summary>
        internal static string Route_ID_0 {
            get {
                return ResourceManager.GetString("Route_ID_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם קו לא מוגדר.
        /// </summary>
        internal static string Route_Name_Empty {
            get {
                return ResourceManager.GetString("Route_Name_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סוג קו לא מוגדר.
        /// </summary>
        internal static string Route_Type_0 {
            get {
                return ResourceManager.GetString("Route_Type_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מסלול לא מוגדר.
        /// </summary>
        internal static string Route_Type_Empty {
            get {
                return ResourceManager.GetString("Route_Type_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קו לא נמצא במאגר של קוים.
        /// </summary>
        internal static string RouteLine_Foreign_Not_Found {
            get {
                return ResourceManager.GetString("RouteLine_Foreign_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר קו לא יכול להיות 0.
        /// </summary>
        internal static string RouteNumber_0 {
            get {
                return ResourceManager.GetString("RouteNumber_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר קו לא מוגדר.
        /// </summary>
        internal static string RouteNumber_Empty {
            get {
                return ResourceManager.GetString("RouteNumber_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם עונה לא מוגדר.
        /// </summary>
        internal static string Seasonal_Empty {
            get {
                return ResourceManager.GetString("Seasonal_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סוג שרות לא מוגדר.
        /// </summary>
        internal static string Service_Type_Empty {
            get {
                return ResourceManager.GetString("Service_Type_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שילוט של מוגדר.
        /// </summary>
        internal static string Signpost_Empty {
            get {
                return ResourceManager.GetString("Signpost_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מקט תחנה לא מוגדר.
        /// </summary>
        internal static string StationCatalog_Empty {
            get {
                return ResourceManager.GetString("StationCatalog_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סטטוס תחנה לא מוגדר.
        /// </summary>
        internal static string StationStatus_0 {
            get {
                return ResourceManager.GetString("StationStatus_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מטיפוס תחנה לא מוגדר.
        /// </summary>
        internal static string StationType_0 {
            get {
                return ResourceManager.GetString("StationType_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם תחנה בקו לא הוגדר.
        /// </summary>
        internal static string Stop_Name_Empty {
            get {
                return ResourceManager.GetString("Stop_Name_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} - {0}.
        /// </summary>
        internal static string ValidationResultString {
            get {
                return ResourceManager.GetString("ValidationResultString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חלופה לא מוגדרת.
        /// </summary>
        internal static string Var_Empty {
            get {
                return ResourceManager.GetString("Var_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גודל אוטובוס לא מוגדר.
        /// </summary>
        internal static string Vehicle_Size_Empty {
            get {
                return ResourceManager.GetString("Vehicle_Size_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ללא workspace.
        /// </summary>
        internal static string WorkspaceNotDefined {
            get {
                return ResourceManager.GetString("WorkspaceNotDefined", resourceCulture);
            }
        }
    }
}
