//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RouteExportProcess.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceGUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceGUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RouteExportProcess.Resources.ResourceGUI", typeof(ResourceGUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תהליך ייצוא של מפה לסיס הנתונים של השוואות יימשך מספר דקות האם ברצונך להמשיך.
        /// </summary>
        internal static string AdminExportQuestions {
            get {
                return ResourceManager.GetString("AdminExportQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אפליקציה כבר רצה.
        /// </summary>
        internal static string ApplicationAlreadyRunning {
            get {
                return ResourceManager.GetString("ApplicationAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם ברצונך לסגור את המערכת.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קובצי ההמרה נוצרו בהצלחה.
        /// </summary>
        internal static string CatalogConvertedFileWasCreatedSuccesefully {
            get {
                return ResourceManager.GetString("CatalogConvertedFileWasCreatedSuccesefully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סינון לפי מקטים.
        /// </summary>
        internal static string CatalogFilter {
            get {
                return ResourceManager.GetString("CatalogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עדכון מקט - {0} .
        /// </summary>
        internal static string CatalogManage {
            get {
                return ResourceManager.GetString("CatalogManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מקט כזה כבר קיים לאשכול, נא לבחור במקט אחר.
        /// </summary>
        internal static string CatlogWithSameRNandClusterAlreadyDefined {
            get {
                return ResourceManager.GetString("CatlogWithSameRNandClusterAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא, לסגור אפליקציה ולפתוח אותה שנית על מנת לקבל את השינוים.
        /// </summary>
        internal static string ChangeAdminDone {
            get {
                return ResourceManager.GetString("ChangeAdminDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם ברצונך לחשב מחדש תחנות הורדה בקו.
        /// </summary>
        internal static string ChangeHoradaStationsForAllLone {
            get {
                return ResourceManager.GetString("ChangeHoradaStationsForAllLone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם לשנות תצוגה של מפה.
        /// </summary>
        internal static string ChangeLayers {
            get {
                return ResourceManager.GetString("ChangeLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תצוגה של מפה השתנה בהצלחה.
        /// </summary>
        internal static string ChangingLayersSuccess {
            get {
                return ResourceManager.GetString("ChangingLayersSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא, לבחור קבוצת התחשבנות.
        /// </summary>
        internal static string ChooseAccountingGroup {
            get {
                return ResourceManager.GetString("ChooseAccountingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא, בחר מקט קיים.
        /// </summary>
        internal static string ChooseCatalog {
            get {
                return ResourceManager.GetString("ChooseCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא, לבחור אשכול.
        /// </summary>
        internal static string ChooseCluster {
            get {
                return ResourceManager.GetString("ChooseCluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר אשכולות שאותם ברצונך לייצא.
        /// </summary>
        internal static string ChooseClustersForExportAndGoOnWithExport {
            get {
                return ResourceManager.GetString("ChooseClustersForExportAndGoOnWithExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר ספריה שבה יווצר קובץ ההמרה.
        /// </summary>
        internal static string ChooseConvertCatalogFolder {
            get {
                return ResourceManager.GetString("ChooseConvertCatalogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחירת קובץ לקליטה של אנד פוינט בפורמט לונג,לט,נוד יד.
        /// </summary>
        internal static string ChooseEndPointFileFormat {
            get {
                return ResourceManager.GetString("ChooseEndPointFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר ספריה שבה יווצר הקובץ .
        /// </summary>
        internal static string ChooseExportToExcelFolder {
            get {
                return ResourceManager.GetString("ChooseExportToExcelFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר ספריה שבה יווצר קובץ של גרסת מוקד.
        /// </summary>
        internal static string ChooseJunctionVersionFileBuilddFolder {
            get {
                return ResourceManager.GetString("ChooseJunctionVersionFileBuilddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא, לבחור מספר קו.
        /// </summary>
        internal static string ChooseRouteNumber {
            get {
                return ResourceManager.GetString("ChooseRouteNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר ספריה שבה יווצר קובץ של ניתוח אזורי מחיר של תחנות.
        /// </summary>
        internal static string ChooseStationAreaPriceReportVersionFileBuilddFolder {
            get {
                return ResourceManager.GetString("ChooseStationAreaPriceReportVersionFileBuilddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא, לבחור בסוג תחנה.
        /// </summary>
        internal static string ChooseStationType {
            get {
                return ResourceManager.GetString("ChooseStationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא הנמצאו אזורים מוניציפאלי הסמוכים לתחנה זו.
        /// </summary>
        internal static string CloseAreNotFound {
            get {
                return ResourceManager.GetString("CloseAreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סינון לפי אשכול.
        /// </summary>
        internal static string ClustertFilter {
            get {
                return ResourceManager.GetString("ClustertFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עדכון עבר בהצלחה.
        /// </summary>
        internal static string ClusterValidExportSucceded {
            get {
                return ResourceManager.GetString("ClusterValidExportSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר קבוצת התחשבנות.
        /// </summary>
        internal static string cmbAccountingGroupIsEmpty {
            get {
                return ResourceManager.GetString("cmbAccountingGroupIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר אשכול.
        /// </summary>
        internal static string cmbClusternameIsEmpty {
            get {
                return ResourceManager.GetString("cmbClusternameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר סוג ייחדיות.
        /// </summary>
        internal static string cmbExclusivityIsEmpty {
            get {
                return ResourceManager.GetString("cmbExclusivityIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר עונתיות.
        /// </summary>
        internal static string cmbExclusivityLineTypeIsEmpty {
            get {
                return ResourceManager.GetString("cmbExclusivityLineTypeIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  בחר סוג קו.
        /// </summary>
        internal static string cmbRouteTypeIsEmpty {
            get {
                return ResourceManager.GetString("cmbRouteTypeIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר סוג שרות.
        /// </summary>
        internal static string cmbServiceTypeIsEmpty {
            get {
                return ResourceManager.GetString("cmbServiceTypeIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר מחוז ראשי.
        /// </summary>
        internal static string cmbZoneheadIsEmpty {
            get {
                return ResourceManager.GetString("cmbZoneheadIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר מחוז משנה.
        /// </summary>
        internal static string cmbZoneSubHeadIsEmpty {
            get {
                return ResourceManager.GetString("cmbZoneSubHeadIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קובץ קונפיגורציה לא הוגדר נכון עבור תהליך ייצוא.
        /// </summary>
        internal static string ConfigurationExportMechanismWasNotDefined {
            get {
                return ResourceManager.GetString("ConfigurationExportMechanismWasNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שינוי של מקט יביא לשינוי פרמטרים הקשורים למקט..
        /// </summary>
        internal static string ConfirmChangingCatalog {
            get {
                return ResourceManager.GetString("ConfirmChangingCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם למחוק רשומה.
        /// </summary>
        internal static string ConfirmDeleteRow {
            get {
                return ResourceManager.GetString("ConfirmDeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם ברצונך לשמור שינוים שביצעת בקו.
        /// </summary>
        internal static string ConfirmRouteLineSave {
            get {
                return ResourceManager.GetString("ConfirmRouteLineSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם ברצונך לשמור שינוים בביצעת בקו תחנה.
        /// </summary>
        internal static string ConfirmRouteStopSave {
            get {
                return ResourceManager.GetString("ConfirmRouteStopSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המרה של קובץ בפורמט שייפ לטאב.
        /// </summary>
        internal static string convertIstrShapeToTab {
            get {
                return ResourceManager.GetString("convertIstrShapeToTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הרצת מקרו לבניית קבצי גאוגרפיה .
        /// </summary>
        internal static string CreateExportShapeFiles {
            get {
                return ResourceManager.GetString("CreateExportShapeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר קובץ csv ללא כותרות.
        /// </summary>
        internal static string CSVFileJunctionVersionNonHeader {
            get {
                return ResourceManager.GetString("CSVFileJunctionVersionNonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך לא תיקני.
        /// </summary>
        internal static string DateNotValid {
            get {
                return ResourceManager.GetString("DateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא, מחק כל הקבצים שנמצאים בספריה לאחר הרצת קליטת התשתיות.
        /// </summary>
        internal static string DeleteFolderContentAfterRunningBaseExport {
            get {
                return ResourceManager.GetString("DeleteFolderContentAfterRunningBaseExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם בכוונתך למחוק.
        /// </summary>
        internal static string DeleteLogin {
            get {
                return ResourceManager.GetString("DeleteLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מזהה הקו וכל התחנות שלו יבוטלו , האם אתה בטוח .
        /// </summary>
        internal static string DeleteRouteLineConfirmation {
            get {
                return ResourceManager.GetString("DeleteRouteLineConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קו {0} נמחק בהצלחהו .
        /// </summary>
        internal static string DeleteRouteLineSuccessInfo {
            get {
                return ResourceManager.GetString("DeleteRouteLineSuccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תחנה זו תבוטל. האם אתה בטוח.
        /// </summary>
        internal static string DeleteRouteStopConfirmation {
            get {
                return ResourceManager.GetString("DeleteRouteStopConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תחנת הקו נמחקה בהצלחה.
        /// </summary>
        internal static string DeleteRouteStopSuccessInfo {
            get {
                return ResourceManager.GetString("DeleteRouteStopSuccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הפצת התשתיות לא הסתיימה באופן תקין. נא בדוק דוח שמוצג..
        /// </summary>
        internal static string DistributionInfrastructureVerifiedFailed {
            get {
                return ResourceManager.GetString("DistributionInfrastructureVerifiedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הפצת התשתיות הסתיימה תקין.
        /// </summary>
        internal static string DistributionInfrastructureVerifiedSuccesefully {
            get {
                return ResourceManager.GetString("DistributionInfrastructureVerifiedSuccesefully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הקלק פעמים על מנת לראות דוח פרטני.
        /// </summary>
        internal static string DoubleClickToSeeReport {
            get {
                return ResourceManager.GetString("DoubleClickToSeeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שיכפול מי קו מספר {0} ,שם {0} כקו חדש.
        /// </summary>
        internal static string DuplicatedLine {
            get {
                return ResourceManager.GetString("DuplicatedLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן להפעיל מחיקה של תחנה אצל מפעיל אגד.
        /// </summary>
        internal static string EgedDeleteStationIsProhibited {
            get {
                return ResourceManager.GetString("EgedDeleteStationIsProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מפת אגד נקלטה בהצלחה.
        /// </summary>
        internal static string EgedMadWasSuccesefullyLoaded {
            get {
                return ResourceManager.GetString("EgedMadWasSuccesefullyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הצג מידע של קו.
        /// </summary>
        internal static string EgedShowRouteGISInfo {
            get {
                return ResourceManager.GetString("EgedShowRouteGISInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם ברצונך לאפשר לעבוד עם תפריט של אזורי מחיר.
        /// </summary>
        internal static string EnableAreaPriceMenu {
            get {
                return ResourceManager.GetString("EnableAreaPriceMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מקליטה של אנד פוינט ותחנות פיזיות הסתיימה בהצלחה.
        /// </summary>
        internal static string EndPointsAndPhysicalStopsWasSuccesefullyLoaded {
            get {
                return ResourceManager.GetString("EndPointsAndPhysicalStopsWasSuccesefullyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ישנן תחנות פיזיות שגויות. ראה אתם בדוח שיופק.
        /// </summary>
        internal static string ERROR_PHYSICAL_STOP_BEFORE_SQL_EXPORT {
            get {
                return ResourceManager.GetString("ERROR_PHYSICAL_STOP_BEFORE_SQL_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קוים שגוים.
        /// </summary>
        internal static string ErrorLinesReportCaption {
            get {
                return ResourceManager.GetString("ErrorLinesReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תחנות פיזיות שגויות.
        /// </summary>
        internal static string ErrorPhysicalReportCaption {
            get {
                return ResourceManager.GetString("ErrorPhysicalReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קו  {0} מכיל {1} שגיאות.
        /// </summary>
        internal static string ErrorRouteLine {
            get {
                return ResourceManager.GetString("ErrorRouteLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר קוים {0} לא תקינים .
        /// </summary>
        internal static string ErrorRouteLineCount {
            get {
                return ResourceManager.GetString("ErrorRouteLineCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר תחנות פיזיות {0} לא תקינות.
        /// </summary>
        internal static string ErrorRoutePhysicalStopsCount {
            get {
                return ResourceManager.GetString("ErrorRoutePhysicalStopsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קו תחנה {0} מכיל {1} שגיאות.
        /// </summary>
        internal static string ErrorRouteStop {
            get {
                return ResourceManager.GetString("ErrorRouteStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר תחנות בקו {0} לא תקינות.
        /// </summary>
        internal static string ErrorRouteStopsCount {
            get {
                return ResourceManager.GetString("ErrorRouteStopsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תחנות הקו שגוים.
        /// </summary>
        internal static string ErrorStopsReportCaption {
            get {
                return ResourceManager.GetString("ErrorStopsReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יציאה מהמערכת.
        /// </summary>
        internal static string ExitFromApplication {
            get {
                return ResourceManager.GetString("ExitFromApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם להתחיל בתהליך היצוא של תשתיות.
        /// </summary>
        internal static string ExportBaseDataQuestions {
            get {
                return ResourceManager.GetString("ExportBaseDataQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קובץ אקסל נוצר בספריה {0}..
        /// </summary>
        internal static string ExportExcelCreated {
            get {
                return ResourceManager.GetString("ExportExcelCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תהליך יצוא הסתיים בהצלחה האם ברצונך לראות קבצים שנוצרו.
        /// </summary>
        internal static string ExportProcessWasSucceseful {
            get {
                return ResourceManager.GetString("ExportProcessWasSucceseful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תהליך יצוא הסתיים בהצלחה.
        /// </summary>
        internal static string ExportProcessWasSuccesefulNonQuestion {
            get {
                return ResourceManager.GetString("ExportProcessWasSuccesefulNonQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תהליך היצוא הסתיים בהצלחה.
        /// </summary>
        internal static string ExportProcessWasSuccesefulSQL {
            get {
                return ResourceManager.GetString("ExportProcessWasSuccesefulSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם להתחיל בתהליך היצוא של מפה.
        /// </summary>
        internal static string ExportQuestions {
            get {
                return ResourceManager.GetString("ExportQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ייצוא נתונים למערכת רישוי חסום.
        /// </summary>
        internal static string ExportToRishuiLocked {
            get {
                return ResourceManager.GetString("ExportToRishuiLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התהליך היצוא יקח מספר דקות. האם להמשיך.
        /// </summary>
        internal static string ExportToSQLServer {
            get {
                return ResourceManager.GetString("ExportToSQLServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תקין.
        /// </summary>
        internal static string Fix {
            get {
                return ResourceManager.GetString("Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קו  {0} תקין.
        /// </summary>
        internal static string GoodRouteLine {
            get {
                return ResourceManager.GetString("GoodRouteLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קו תחנה {0} תקין.
        /// </summary>
        internal static string GoodRouteStop {
            get {
                return ResourceManager.GetString("GoodRouteStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אשכול לא מוגדר בקובץ אשקולות למחוז. נא, הגדר אותו.
        /// </summary>
        internal static string IdClusterNotDefinedInClusterToZoneFile {
            get {
                return ResourceManager.GetString("IdClusterNotDefinedInClusterToZoneFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מס מחוז רארשי.
        /// </summary>
        internal static string IdMahozMain {
            get {
                return ResourceManager.GetString("IdMahozMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מס מחוז משני.
        /// </summary>
        internal static string IdMahozSub {
            get {
                return ResourceManager.GetString("IdMahozSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שינוי של קבוצת התחשבנות של מזהה קו זה יגרום לשינוי של קבוצת התחשבנות של כול מזהי קוים של אותו מקט..
        /// </summary>
        internal static string LineDetailAccountingGroupConfirmation {
            get {
                return ResourceManager.GetString("LineDetailAccountingGroupConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נספח 1.
        /// </summary>
        internal static string LineDetailCaption {
            get {
                return ResourceManager.GetString("LineDetailCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שינוי של אשכול של מזהה קו זה יגרום לשינוי של אשקולות של כול מזהי קוים של אותו מקט..
        /// </summary>
        internal static string LineDetailEshkolConfirmation {
            get {
                return ResourceManager.GetString("LineDetailEshkolConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} קו {0} לא ניתן לייצא בגלל תאריך תוקף.
        /// </summary>
        internal static string LineErrorValidExportDate {
            get {
                return ResourceManager.GetString("LineErrorValidExportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קו מכיל תחנות הורדה. האם להמשיך בתהליך חישוב ?.
        /// </summary>
        internal static string LineHasHoradaStationDoYouWantToContinue {
            get {
                return ResourceManager.GetString("LineHasHoradaStationDoYouWantToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נתוני קוים  סה&quot;כ {0} קוים.
        /// </summary>
        internal static string LinesDataAccomulation {
            get {
                return ResourceManager.GetString("LinesDataAccomulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מק&quot;ט/ים {1} אינם שייכים למפעיל {0}, כדי לייצא אותם לרישוי, עליך להתחבר עם המפעיל המתאים..
        /// </summary>
        internal static string LinesNotBelongToOperator {
            get {
                return ResourceManager.GetString("LinesNotBelongToOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שיוך תחנה לשטח מוניציפאלי.
        /// </summary>
        internal static string linkstationToMun {
            get {
                return ResourceManager.GetString("linkstationToMun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וודא שקבצים מעודכנים נמצאים בספריה
        ///{0}.
        /// </summary>
        internal static string LoadEgedMap {
            get {
                return ResourceManager.GetString("LoadEgedMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ניהול משתשמים של המערכת.
        /// </summary>
        internal static string LoginManagment {
            get {
                return ResourceManager.GetString("LoginManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן לעדכן חלופה או כיוון כיוון שקיים לוז של קו זה.
        /// </summary>
        internal static string LuzExistsForLine {
            get {
                return ResourceManager.GetString("LuzExistsForLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מידע נוסף.
        /// </summary>
        internal static string mAdditionalInfo {
            get {
                return ResourceManager.GetString("mAdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מנהל תשתיות.
        /// </summary>
        internal static string mAdministrator {
            get {
                return ResourceManager.GetString("mAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם מחוז ראשי.
        /// </summary>
        internal static string MahozMainName {
            get {
                return ResourceManager.GetString("MahozMainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם מחוז משני.
        /// </summary>
        internal static string MahozSubName {
            get {
                return ResourceManager.GetString("MahozSubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טרנסקאד – מפת תח&quot;צ&quot;. {0} משתמש {1} , מפעיל {2}, אשקול {3} .
        /// </summary>
        internal static string MainFormCaption {
            get {
                return ResourceManager.GetString("MainFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המפה נמדדת ב {0} יחידות.
        /// </summary>
        internal static string MapUnits {
            get {
                return ResourceManager.GetString("MapUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קליטת מפה של אגד.
        /// </summary>
        internal static string mEgedMapLoad {
            get {
                return ResourceManager.GetString("mEgedMapLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ייצוא.
        /// </summary>
        internal static string mExport {
            get {
                return ResourceManager.GetString("mExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to איזורי מחיר.
        /// </summary>
        internal static string mPriceList {
            get {
                return ResourceManager.GetString("mPriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חדש.
        /// </summary>
        internal static string NewRecordsCount {
            get {
                return ResourceManager.GetString("NewRecordsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נספח 1 , מפעיל - {0}..
        /// </summary>
        internal static string Nispah1Form {
            get {
                return ResourceManager.GetString("Nispah1Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כל הקוים תקינים.
        /// </summary>
        internal static string NOT_ERROR_LINES {
            get {
                return ResourceManager.GetString("NOT_ERROR_LINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כל תחנות בקו תקינות.
        /// </summary>
        internal static string NOT_ERROR_LINES_STOP {
            get {
                return ResourceManager.GetString("NOT_ERROR_LINES_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כל תחנות פיזיות תקינות.
        /// </summary>
        internal static string NOT_ERROR_PHYSICAL_STOP {
            get {
                return ResourceManager.GetString("NOT_ERROR_PHYSICAL_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שגוי.
        /// </summary>
        internal static string NOT_Fix {
            get {
                return ResourceManager.GetString("NOT_Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שדה זה מכיל רק ערכים נומרים.
        /// </summary>
        internal static string NumericValueOnly {
            get {
                return ResourceManager.GetString("NumericValueOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} שם מפעיל.
        /// </summary>
        internal static string OperatorName {
            get {
                return ResourceManager.GetString("OperatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המפעיל שבחרת לא הומר לפורמט החדש.
        /// </summary>
        internal static string OperatorWasNotConverted {
            get {
                return ResourceManager.GetString("OperatorWasNotConverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא, לבחור מפעיל.
        /// </summary>
        internal static string OperatorWasNotSelected {
            get {
                return ResourceManager.GetString("OperatorWasNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תחנות פיזיות סה&quot;כ {0}.
        /// </summary>
        internal static string PhisicalStopsDataAccomulation {
            get {
                return ResourceManager.GetString("PhisicalStopsDataAccomulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  חברת תכנון .
        /// </summary>
        internal static string PlanningFirm {
            get {
                return ResourceManager.GetString("PlanningFirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא, לבחור בספריית של קובץ ההמרה.
        /// </summary>
        internal static string PleaseChooseConvertCatalogFolder {
            get {
                return ResourceManager.GetString("PleaseChooseConvertCatalogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קובץ מיקום תחנה נוצר בהצלחה.
        /// </summary>
        internal static string PriceListFileCreatedSuccefully {
            get {
                return ResourceManager.GetString("PriceListFileCreatedSuccefully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תהליך העברת אזורי מחיר הסתיים בהצלחה.
        /// </summary>
        internal static string PriceListPassedSuccesefuly {
            get {
                return ResourceManager.GetString("PriceListPassedSuccesefuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תהליך ייצוא של אזורי מחיר יקח כמה דקות. האם לבצע.
        /// </summary>
        internal static string PriceListPocessRunning {
            get {
                return ResourceManager.GetString("PriceListPocessRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם הקו: {0}.
        /// </summary>
        internal static string RouteLineDetails {
            get {
                return ResourceManager.GetString("RouteLineDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא נבחרו קוים.
        /// </summary>
        internal static string RouteLineListEmpty {
            get {
                return ResourceManager.GetString("RouteLineListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סינון לפי מספר קו.
        /// </summary>
        internal static string RouteNumberFilter {
            get {
                return ResourceManager.GetString("RouteNumberFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נספח 3.
        /// </summary>
        internal static string RouteStopDetailCaption {
            get {
                return ResourceManager.GetString("RouteStopDetailCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פעולת שמירה נכשלה, ראה פירוט של הבעיות.
        /// </summary>
        internal static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תהליך שמירת נתוני תשתית הסתיים בהצלחה.
        /// </summary>
        internal static string SaveImportToLocalWasSuccesefullyFinished {
            get {
                return ResourceManager.GetString("SaveImportToLocalWasSuccesefullyFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התהליך שמירה יקח מספר דקות. האם להמשיך.
        /// </summary>
        internal static string SaveInfraToLocalStorage {
            get {
                return ResourceManager.GetString("SaveInfraToLocalStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרטי קו {0} נשמרו בהצלחה.
        /// </summary>
        internal static string SaveRouteLineDoneWithSuccese {
            get {
                return ResourceManager.GetString("SaveRouteLineDoneWithSuccese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרטי קו תחנה נשמרו בהצלחה.
        /// </summary>
        internal static string SaveRouteStopDoneWithSucces {
            get {
                return ResourceManager.GetString("SaveRouteStopDoneWithSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא, לבחור עיר.
        /// </summary>
        internal static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר ספריה שבה יווצרו קובצי אגד.
        /// </summary>
        internal static string SelectEgedFolderCSVFile {
            get {
                return ResourceManager.GetString("SelectEgedFolderCSVFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר שם של קובץ.
        /// </summary>
        internal static string SelectFileImageNameToSave {
            get {
                return ResourceManager.GetString("SelectFileImageNameToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר מחוז לקו.
        /// </summary>
        internal static string SelectMahozForStateSelect {
            get {
                return ResourceManager.GetString("SelectMahozForStateSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא, לבחור במחוז ראשי ומשני.
        /// </summary>
        internal static string SelectMahozMainAndSub {
            get {
                return ResourceManager.GetString("SelectMahozMainAndSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא, לבחור תחילה מפעיל ואשכול.
        /// </summary>
        internal static string SelectOperatprAndCluster {
            get {
                return ResourceManager.GetString("SelectOperatprAndCluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא בחרת תאריך האם להמשיך.
        /// </summary>
        internal static string SelectOperatprAndClusterWhenValidDateEmptyConfirm {
            get {
                return ResourceManager.GetString("SelectOperatprAndClusterWhenValidDateEmptyConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא, לסמן רשומות לעדכון.
        /// </summary>
        internal static string SelectRowsForUpdate {
            get {
                return ResourceManager.GetString("SelectRowsForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא, לבחור תחנה.
        /// </summary>
        internal static string SelectStation {
            get {
                return ResourceManager.GetString("SelectStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר קובץ של תחנות.
        /// </summary>
        internal static string SelectStationCSVFile {
            get {
                return ResourceManager.GetString("SelectStationCSVFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר קובץ של תחנות עבור תהליך בדיקת שינוי תחנה באזור מחיר.
        /// </summary>
        internal static string SelectStationCSVFileOfProcessAreaPriceNewLocation {
            get {
                return ResourceManager.GetString("SelectStationCSVFileOfProcessAreaPriceNewLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר קובץ תחנות עבור תהליך קליטת עדכון שיוך תחנות לאזורי מחיר.
        /// </summary>
        internal static string SelectStationCSVFileOfProcessExportSationToPriceAreaAllOperators {
            get {
                return ResourceManager.GetString("SelectStationCSVFileOfProcessExportSationToPriceAreaAllOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תהליך ייצוא ל SQL Server נכשל \n {0}.
        /// </summary>
        internal static string SQLServerExportWasFailed {
            get {
                return ResourceManager.GetString("SQLServerExportWasFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תהליך ייצוא ל SQL Server הסתיים בהצלחה.
        /// </summary>
        internal static string SQLServerExportWasSuccesefullyFinished {
            get {
                return ResourceManager.GetString("SQLServerExportWasSuccesefullyFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סינון לפי מקט תחנה.
        /// </summary>
        internal static string StationCatalogFilter {
            get {
                return ResourceManager.GetString("StationCatalogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מס&apos; תחנות {0}.
        /// </summary>
        internal static string StationCountString {
            get {
                return ResourceManager.GetString("StationCountString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סינון לפי שם תחנה.
        /// </summary>
        internal static string StationNameFilter {
            get {
                return ResourceManager.GetString("StationNameFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לקו לא נבחרו תחנות.
        /// </summary>
        internal static string StationNoneForTheLine {
            get {
                return ResourceManager.GetString("StationNoneForTheLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תחנה שויכה בהצלחה לאזור מוניציפאלי.
        /// </summary>
        internal static string StationWasSuccesefullyLinked {
            get {
                return ResourceManager.GetString("StationWasSuccesefullyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נתוני תחנות בקו  סה&quot;כ {0} תחנות בקו.
        /// </summary>
        internal static string StopsDataAccomulation {
            get {
                return ResourceManager.GetString("StopsDataAccomulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to צרף רוט סיסטם של כול המפעילים.
        /// </summary>
        internal static string submAppendOperatorRouteSystems {
            get {
                return ResourceManager.GetString("submAppendOperatorRouteSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בנה קובץ לקביעת מספר המוקדים בקו.
        /// </summary>
        internal static string submBuildLineJunctionFile {
            get {
                return ResourceManager.GetString("submBuildLineJunctionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חשב תחנת הורדה ראשונה לכל ה-RS..
        /// </summary>
        internal static string submCalcFirstDropStationForAllSystem {
            get {
                return ResourceManager.GetString("submCalcFirstDropStationForAllSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בדוק מזהי קווים ותחנות לפני ייצוא לרישוי.
        /// </summary>
        internal static string submCheckMapBeforeExport {
            get {
                return ResourceManager.GetString("submCheckMapBeforeExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ניהול תאריכי ייצוא של אשכולות.
        /// </summary>
        internal static string submClusterValidDateExportManage {
            get {
                return ResourceManager.GetString("submClusterValidDateExportManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דוח תאריכי ייצוא לרישוי.
        /// </summary>
        internal static string submClusterValidDateExportManageOfOperator {
            get {
                return ResourceManager.GetString("submClusterValidDateExportManageOfOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ייצוא של נתוני מסלולים של אגד.
        /// </summary>
        internal static string submEgedExportProcess {
            get {
                return ResourceManager.GetString("submEgedExportProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לאפשר לעבוד עם תפריטים של אזורי מחיר.
        /// </summary>
        internal static string submEnablePriceListToLicensingSystem {
            get {
                return ResourceManager.GetString("submEnablePriceListToLicensingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ייצא תשתיות למערכת הרישוי.
        /// </summary>
        internal static string submExportBaseDasaToLicensing {
            get {
                return ResourceManager.GetString("submExportBaseDasaToLicensing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ייצא את תחנות אגד.
        /// </summary>
        internal static string submExportEggedStations {
            get {
                return ResourceManager.GetString("submExportEggedStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ייצא רשימת קווים לקובץ אקסל.
        /// </summary>
        internal static string submExportLinesToExcel {
            get {
                return ResourceManager.GetString("submExportLinesToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ייצא מזהי קווים לרישוי.
        /// </summary>
        internal static string submExportLinesToLicensingSystem {
            get {
                return ResourceManager.GetString("submExportLinesToLicensingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ייצא מפה להשוואה לבסיס הנתונים.
        /// </summary>
        internal static string submExportMapForDataComparing {
            get {
                return ResourceManager.GetString("submExportMapForDataComparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ייצא מפה לקובץ תמונה.
        /// </summary>
        internal static string submExportMapToImage {
            get {
                return ResourceManager.GetString("submExportMapToImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ייצוא של אזורי מחיר למערכת רישוי.
        /// </summary>
        internal static string submExportPriceListToLicensingSystem {
            get {
                return ResourceManager.GetString("submExportPriceListToLicensingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קליטת עדכון שיוך תחנות לאיזור המחיר.
        /// </summary>
        internal static string submExportStationLinkedToPriceArea {
            get {
                return ResourceManager.GetString("submExportStationLinkedToPriceArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קליטת אזורי מחיר.
        /// </summary>
        internal static string submExportStationPriceAreaImport {
            get {
                return ResourceManager.GetString("submExportStationPriceAreaImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קליטת מפה של אגד.
        /// </summary>
        internal static string submImportEgedMap {
            get {
                return ResourceManager.GetString("submImportEgedMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קליטה של טבלה אנד פוינט ותחנות פיזיות.
        /// </summary>
        internal static string submImportEndPointsAndPhysicalStops {
            get {
                return ResourceManager.GetString("submImportEndPointsAndPhysicalStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קבע מזהה קו בסיסי.
        /// </summary>
        internal static string submSetBasedLine {
            get {
                return ResourceManager.GetString("submSetBasedLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הצג שכבות נוספות במפה.
        /// </summary>
        internal static string submShowAdditionalLayersInMap {
            get {
                return ResourceManager.GetString("submShowAdditionalLayersInMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הצג קובץ קונפיגורציה.
        /// </summary>
        internal static string submShowConfigFile {
            get {
                return ResourceManager.GetString("submShowConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הצג קודי המרה של מערכת הרישוי.
        /// </summary>
        internal static string submShowConvertCodesOfBasedTable {
            get {
                return ResourceManager.GetString("submShowConvertCodesOfBasedTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הצג קווים העוברים בתחנה.
        /// </summary>
        internal static string submShowLinesPassingViaStation {
            get {
                return ResourceManager.GetString("submShowLinesPassingViaStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בדיקת שינוי תחנה באזור מחיר.
        /// </summary>
        internal static string submStationAreaPriceChange {
            get {
                return ResourceManager.GetString("submStationAreaPriceChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עדכון פרטים של אזורי מחיר.
        /// </summary>
        internal static string submUpdateAreaPriceDetails {
            get {
                return ResourceManager.GetString("submUpdateAreaPriceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עדכן את שכבת התחנות הפיזיות.
        /// </summary>
        internal static string submUpdatePhysicalStopsLayer {
            get {
                return ResourceManager.GetString("submUpdatePhysicalStopsLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שיוך של תחנות לעיר.
        /// </summary>
        internal static string submUpdateStationLinkToCity {
            get {
                return ResourceManager.GetString("submUpdateStationLinkToCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עדכן את שכבת הרחובות.
        /// </summary>
        internal static string submUpdateStreetLayer {
            get {
                return ResourceManager.GetString("submUpdateStreetLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המערכת בודקת את הנתונים.
        /// </summary>
        internal static string SystemTask {
            get {
                return ResourceManager.GetString("SystemTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תהליך המרה הסתיים בהצלחה, קובץ {0} הועבר לכספת.
        /// </summary>
        internal static string TABFileWasCreated {
            get {
                return ResourceManager.GetString("TABFileWasCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} קובץ טרנסקד.
        /// </summary>
        internal static string TransCadPath {
            get {
                return ResourceManager.GetString("TransCadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר קו לא יכול להכיל אפסים מובילים.
        /// </summary>
        internal static string txtRouteNumberHasFirstZero {
            get {
                return ResourceManager.GetString("txtRouteNumberHasFirstZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא, הכנס מספר קו.
        /// </summary>
        internal static string txtRouteNumberIsEmpty {
            get {
                return ResourceManager.GetString("txtRouteNumberIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שילוט קו לא יכול להכיל אפסים מובילים.
        /// </summary>
        internal static string txtSignPostHasFirstZero {
            get {
                return ResourceManager.GetString("txtSignPostHasFirstZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עדכון של שדה גודל רכב.
        /// </summary>
        internal static string UpdateCarSize {
            get {
                return ResourceManager.GetString("UpdateCarSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עדכון של שדה סוג רכב.
        /// </summary>
        internal static string UpdateCarType {
            get {
                return ResourceManager.GetString("UpdateCarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} שם משתמש .
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קו {0} לא עבר בדיקת תקינות.
        /// </summary>
        internal static string ValidationRouteLineNotPassed {
            get {
                return ResourceManager.GetString("ValidationRouteLineNotPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קו {0} עבר בדיקת תקינות.
        /// </summary>
        internal static string ValidationRouteLinePassed {
            get {
                return ResourceManager.GetString("ValidationRouteLinePassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קו תחנה{0} לא עבר בדיקת תקינות.
        /// </summary>
        internal static string ValidationRouteStopNotPassed {
            get {
                return ResourceManager.GetString("ValidationRouteStopNotPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קו תחנה {0} עבר בדיקת תקינות.
        /// </summary>
        internal static string ValidationRouteStopPassed {
            get {
                return ResourceManager.GetString("ValidationRouteStopPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קו תחנה{0} לא עבר בדיקת תקינות.
        /// </summary>
        internal static string ValidationRouteStopsNotPassed {
            get {
                return ResourceManager.GetString("ValidationRouteStopsNotPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך תוקף ייצוא של אשכול חייב חהיות יותר מהיום.
        /// </summary>
        internal static string ValidExportClusterDateMustBeMoreToday {
            get {
                return ResourceManager.GetString("ValidExportClusterDateMustBeMoreToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חלופה לא נמצאה באוסף של חלופות המותרות לעדכון.
        /// </summary>
        internal static string VariantNotExistsInVarNumberTable {
            get {
                return ResourceManager.GetString("VariantNotExistsInVarNumberTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בדיקות תקינות לאחר הפצת תשתית למפעילים.
        /// </summary>
        internal static string verifyBasedMap {
            get {
                return ResourceManager.GetString("verifyBasedMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן לעשות זום לקבוצה של יותר 100 רשומות.
        /// </summary>
        internal static string YouCantZoomToMoreThen100Lines {
            get {
                return ResourceManager.GetString("YouCantZoomToMoreThen100Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שינוי זה ישפיע על כל המזהים של המקט שבחרת. מספרם מזהים - {0}. האם אתה בטוח.
        /// </summary>
        internal static string YouchangeswillaffectSameRouteLines {
            get {
                return ResourceManager.GetString("YouchangeswillaffectSameRouteLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הגדרת מקט שכבר קיים.
        /// </summary>
        internal static string YouDefinedExistingCatalog {
            get {
                return ResourceManager.GetString("YouDefinedExistingCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא הוגדרו מחוזות פר אשכול בקובץ ההגדרות.
        /// </summary>
        internal static string ZoneNotDefinedinXML {
            get {
                return ResourceManager.GetString("ZoneNotDefinedinXML", resourceCulture);
            }
        }
    }
}
