//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BLManagerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BLManagerResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BLManager.Resources.BLManagerResource", typeof(BLManagerResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current user doesn&apos;t have any AciveDirectory groups defined in the Operator Listg XML file.
        /// </summary>
        internal static string ActiveDirectoryGroupsNotDefinedInOperatorListXML {
            get {
                return ResourceManager.GetString("ActiveDirectoryGroupsNotDefinedInOperatorListXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הכול.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חסרה שכבה פעילה של איזורי מחיר.
        /// </summary>
        internal static string AreaPriceActiveFileNotExists {
            get {
                return ResourceManager.GetString("AreaPriceActiveFileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לאזור {0} לא נרשם שדה שטח אזור.
        /// </summary>
        internal static string AreaPriceAreaIsEmpty {
            get {
                return ResourceManager.GetString("AreaPriceAreaIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עליך לבקש שכבה חדשה ממשרד התחבורה.
        /// </summary>
        internal static string AreaPriceAskNewSet {
            get {
                return ResourceManager.GetString("AreaPriceAskNewSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עדכון שדות גאומטריה של השכבה.
        /// </summary>
        internal static string AreaPriceExportGISOperations {
            get {
                return ResourceManager.GetString("AreaPriceExportGISOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to העתקת הקבצים לספריה קבועה ומחיקת קבצים זמניים.
        /// </summary>
        internal static string AreaPriceExportMovingFiles {
            get {
                return ResourceManager.GetString("AreaPriceExportMovingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הרצת תהליך ייצוא של אזורי מחיר לרישוי.
        /// </summary>
        internal static string AreaPriceExportProcess {
            get {
                return ResourceManager.GetString("AreaPriceExportProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שמות השדות בקובץ אינם זהים שם הנדרש.
        /// </summary>
        internal static string AreaPriceFieldsNotExists {
            get {
                return ResourceManager.GetString("AreaPriceFieldsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to איזורי מחיר פעיל נמצא בשימוש.
        /// </summary>
        internal static string AreaPriceFileInUse {
            get {
                return ResourceManager.GetString("AreaPriceFileInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חסרים קבצים לצורך קליטת אזורי המחיר.
        /// </summary>
        internal static string AreaPriceFileNotExists {
            get {
                return ResourceManager.GetString("AreaPriceFileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספרי אזור {0} כפולים.
        /// </summary>
        internal static string AreaPriceIDDuplicated {
            get {
                return ResourceManager.GetString("AreaPriceIDDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לאזור {0} לא נרשם מספר אזור.
        /// </summary>
        internal static string AreaPriceIDIsEmpty {
            get {
                return ResourceManager.GetString("AreaPriceIDIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לאזור {0} לא נרשם שם אזור.
        /// </summary>
        internal static string AreaPriceIDWithEmptyName {
            get {
                return ResourceManager.GetString("AreaPriceIDWithEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שכבה של אזורי מחיר ריקה מתוכן.
        /// </summary>
        internal static string AreaPriceLayerEmpty {
            get {
                return ResourceManager.GetString("AreaPriceLayerEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טעינת נתונים של השכבה.
        /// </summary>
        internal static string AreaPriceLoadData {
            get {
                return ResourceManager.GetString("AreaPriceLoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שמות אזור {0} כפולים.
        /// </summary>
        internal static string AreaPriceNameDuplicated {
            get {
                return ResourceManager.GetString("AreaPriceNameDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בדיקת נתונים של הקובץ.
        /// </summary>
        internal static string AreaPriceValidData {
            get {
                return ResourceManager.GetString("AreaPriceValidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בדיקת שמות השדות.
        /// </summary>
        internal static string AreaPriceValidFileFields {
            get {
                return ResourceManager.GetString("AreaPriceValidFileFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בדיקת שמות הקבצים.
        /// </summary>
        internal static string AreaPriceValidFileNames {
            get {
                return ResourceManager.GetString("AreaPriceValidFileNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם הקובץ זיפ לא תואם לשם {0} שנקבע.
        /// </summary>
        internal static string AreaPriceZipNameWrong {
            get {
                return ResourceManager.GetString("AreaPriceZipNameWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בניית נתונים של ערים עבור בסיס הנתונים.
        /// </summary>
        internal static string BuildingDataOfTranscadCity {
            get {
                return ResourceManager.GetString("BuildingDataOfTranscadCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בניית נתונים של צמתים עבור בסיס הנתונים.
        /// </summary>
        internal static string BuildingDataOfTranscadJunction {
            get {
                return ResourceManager.GetString("BuildingDataOfTranscadJunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בניית נתונים של תחנות עבור בסיס הנתונים.
        /// </summary>
        internal static string BuildingDataOfTranscadStation {
            get {
                return ResourceManager.GetString("BuildingDataOfTranscadStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הרצת מקרו לבניית קבצי shape.
        /// </summary>
        internal static string BuildingShapeFileTranscadMacro {
            get {
                return ResourceManager.GetString("BuildingShapeFileTranscadMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לתחנה שויך עיר  {0}. תחילה יש להוריד שיוך קיים.
        /// </summary>
        internal static string CantLinkAlreadyLinkedItem {
            get {
                return ResourceManager.GetString("CantLinkAlreadyLinkedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תחנה לא שייכת לשום עיר..
        /// </summary>
        internal static string CantUnLinkAlreadyUnLinkedItem {
            get {
                return ResourceManager.GetString("CantUnLinkAlreadyUnLinkedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מקט.
        /// </summary>
        internal static string Catalog {
            get {
                return ResourceManager.GetString("Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מקט כבר עבר המרה ל 7 פוזיציות.
        /// </summary>
        internal static string CatalogIsUpdated {
            get {
                return ResourceManager.GetString("CatalogIsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא הוגדר רציף לתחנה.
        /// </summary>
        internal static string CentralStationFloorAndPlatformNotDefined {
            get {
                return ResourceManager.GetString("CentralStationFloorAndPlatformNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר רציף לא קיים בתחנה זו.
        /// </summary>
        internal static string CentralStationPlatformNotDefined {
            get {
                return ResourceManager.GetString("CentralStationPlatformNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רשימת הערים ריקה.
        /// </summary>
        internal static string CityListIsNull {
            get {
                return ResourceManager.GetString("CityListIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא, לסגור טראנסכד ולהפעיל תוכנה מחדש.
        /// </summary>
        internal static string CloseTranscadAndRunApplicationAgain {
            get {
                return ResourceManager.GetString("CloseTranscadAndRunApplicationAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שים לב, עדין לא נקבעה תחילת פעילות לאשכול ולכן לא ניתן להעביר אותו לרישוי.
        /// </summary>
        internal static string ClusterNotValidExportDate {
            get {
                return ResourceManager.GetString("ClusterNotValidExportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עדין לא נקבעה תחילת פעילות לאשכול {0} ולכן לא ניתן להעביר אותו לרישוי.
        /// </summary>
        internal static string ClusterOneNotValidExportDate {
            get {
                return ResourceManager.GetString("ClusterOneNotValidExportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000.
        /// </summary>
        internal static string Code0000 {
            get {
                return ResourceManager.GetString("Code0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to צירוף של אשכול, מקט, חלופה וכיוון כבר קיים.
        /// </summary>
        internal static string CombinationofIdCluster_Catalog_SignPost_Var_Dir_MustBeUnique {
            get {
                return ResourceManager.GetString("CombinationofIdCluster_Catalog_SignPost_Var_Dir_MustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן להפוך מקט {0} של אשכול {1} לפורמט של 7 פוזיציות כיוון יש לו מקט במסד הנתונים.
        /// </summary>
        internal static string ConvertNewCatalogProblem {
            get {
                return ResourceManager.GetString("ConvertNewCatalogProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מבנה טבלאות של דן לא מתאים למבנה של מפעילים.
        /// </summary>
        internal static string DanOperMetaDataNotConfirmed {
            get {
                return ResourceManager.GetString("DanOperMetaDataNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ישנן תחנות רכבת עם אותו שם תחנה {0} ומקט תחנה שונים.
        /// </summary>
        internal static string DifferentSationCatalogFor7 {
            get {
                return ResourceManager.GetString("DifferentSationCatalogFor7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מרחק בין זוגות תחנות {0} קטן מ {1} מרטים.
        /// </summary>
        internal static string DistanceBetweenTwoStationLessThen {
            get {
                return ResourceManager.GetString("DistanceBetweenTwoStationLessThen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תחנות זהות של קו {0} וקו {1} .
        /// </summary>
        internal static string DuplicatedStationInPath {
            get {
                return ResourceManager.GetString("DuplicatedStationInPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עדכון של אנד פוינט ותחנות פיזיות בבסיס הנתונים של אגד.
        /// </summary>
        internal static string EgedDBUpdate {
            get {
                return ResourceManager.GetString("EgedDBUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא נמצאו נתונים של קוים במסד הנתונים של אגד.
        /// </summary>
        internal static string EgedLinelDBListEmpty {
            get {
                return ResourceManager.GetString("EgedLinelDBListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן להתחיל בתהליך מכיוון שלא מנצא קובץ
        ///     {0} 
        ///    .
        /// </summary>
        internal static string EgedLoadFailedBcauseFileWasNotFound {
            get {
                return ResourceManager.GetString("EgedLoadFailedBcauseFileWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן להתחיל בתהליך מכיוון שספריית הקלט אינה קיימת.
        /// </summary>
        internal static string EgedLoadFolderDoesNotExists {
            get {
                return ResourceManager.GetString("EgedLoadFolderDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא קיימים נתונים של נספח 3 במסד הנתונים של אגד.
        /// </summary>
        internal static string EgedNispah3DBListEmpty {
            get {
                return ResourceManager.GetString("EgedNispah3DBListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא נמצאו נתונים של תחנות במסד הנתונים של אגד.
        /// </summary>
        internal static string EgedPhysicalDBListEmpty {
            get {
                return ResourceManager.GetString("EgedPhysicalDBListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ישנם מוקדים שלא עברו עדכון של רחובות. נא, הרץ עדכון שכבת הרחובות.
        /// </summary>
        internal static string EndPointsMacroShouldBeRun {
            get {
                return ResourceManager.GetString("EndPointsMacroShouldBeRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בתאריך {0} נוצרו קבצי תשתית של מפעיל {1}.
        /// </summary>
        internal static string ExportBaseEmailBody {
            get {
                return ResourceManager.GetString("ExportBaseEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בתאריך {0} נוצרו קבצי תשתית של מפעיל {1}.
        /// </summary>
        internal static string ExportBaseEmailSubject {
            get {
                return ResourceManager.GetString("ExportBaseEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא התקבלו הגדרות של ייצוא.
        /// </summary>
        internal static string ExportDefWasNotSeccesefully {
            get {
                return ResourceManager.GetString("ExportDefWasNotSeccesefully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תהליך יצוא נכשל בגלל שמפה לא תקינה.
        /// </summary>
        internal static string ExportFaild_NotValidData {
            get {
                return ResourceManager.GetString("ExportFaild_NotValidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תהליך יצוא נכשל בגלל שספרית יצוא לא קיימת.
        /// </summary>
        internal static string ExportFailed_FolderNotExixts {
            get {
                return ResourceManager.GetString("ExportFailed_FolderNotExixts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תהליך יצוא נכשל בגלל שלא נוצרו כל קבצי המפה.
        /// </summary>
        internal static string ExportFailed_NotAllFilesCreated {
            get {
                return ResourceManager.GetString("ExportFailed_NotAllFilesCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בתאריך {0} נוצרו קבצי רישוי של מפעיל {1}.
        /// </summary>
        internal static string ExportMapEmailBody {
            get {
                return ResourceManager.GetString("ExportMapEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בתאריך {0} נוצרו קבצי רישוי של מפעיל {1}.
        /// </summary>
        internal static string ExportMapEmailSubject {
            get {
                return ResourceManager.GetString("ExportMapEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תהליך ייצוא של קובץ {0} לא הצליח בגלל {1}, נא תיידע מנהל מערכת.
        /// </summary>
        internal static string ExportProcessFailed {
            get {
                return ResourceManager.GetString("ExportProcessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך תחילת תוקף צריך להיות פחות מי תאריך סיום תוקף.
        /// </summary>
        internal static string FromValidityMustBeLessThenToValidity {
            get {
                return ResourceManager.GetString("FromValidityMustBeLessThenToValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא מוגדרת תחנת הורדה.
        /// </summary>
        internal static string Horada_0 {
            get {
                return ResourceManager.GetString("Horada_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נמצאו תחנות עם זמני נסיעה שגוים. נא העבר את הדוח שנפתח למנהלן של המערכת לבדיקה. הקליטה נכשלה.
        /// </summary>
        internal static string IllegalStopsFoundIntoTheExportCalculation {
            get {
                return ResourceManager.GetString("IllegalStopsFoundIntoTheExportCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תהליך קליטת קובצי אגד נכשל בגלל בעיות בנתונים. ראה דוח .
        /// </summary>
        internal static string IntegrityProbleInEgedLoad {
            get {
                return ResourceManager.GetString("IntegrityProbleInEgedLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא נמצא מזהה קו בסיסי.
        /// </summary>
        internal static string IsBaseWasNotDefined {
            get {
                return ResourceManager.GetString("IsBaseWasNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא, לחבר תחילה שכבה מוניסיפאלית.
        /// </summary>
        internal static string IsMunNotConnected {
            get {
                return ResourceManager.GetString("IsMunNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא נמצאה תחנה מתוך קבוצה של מקט תחנה {0} עם ערך 1 בשדה IsTrainMainStation..
        /// </summary>
        internal static string IsTrainMainStationFor7WasNotFound {
            get {
                return ResourceManager.GetString("IsTrainMainStationFor7WasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רשימת התחנות שלא נמצאו בטראנסכד  .
        /// </summary>
        internal static string ListOfStationNotFoundInTranscad {
            get {
                return ResourceManager.GetString("ListOfStationNotFoundInTranscad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טעינת נתונים של ערים מתוך טראנסכד.
        /// </summary>
        internal static string LoadTranscadCity {
            get {
                return ResourceManager.GetString("LoadTranscadCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טעינת נתונים של צמתים מתוך טראנסכד.
        /// </summary>
        internal static string LoadTranscadJunction {
            get {
                return ResourceManager.GetString("LoadTranscadJunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טעינת נתונים של תחנות מתוך טראנסכד.
        /// </summary>
        internal static string LoadTranscadStation {
            get {
                return ResourceManager.GetString("LoadTranscadStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מקט 8.
        /// </summary>
        internal static string Makat8 {
            get {
                return ResourceManager.GetString("Makat8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} נתיב לקובץ מפה שגוי .
        /// </summary>
        internal static string MapLayerFilePathWrong {
            get {
                return ResourceManager.GetString("MapLayerFilePathWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} שם של קובץ מפה שגוי.
        /// </summary>
        internal static string MapLayerNameWrong {
            get {
                return ResourceManager.GetString("MapLayerNameWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בבדיקה פיזית של המפה התגלה בעיה : {0}.
        /// </summary>
        internal static string MapsWithErrors {
            get {
                return ResourceManager.GetString("MapsWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שטח ללא שיפוט.
        /// </summary>
        internal static string MunicipalityArea {
            get {
                return ResourceManager.GetString("MunicipalityArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא מוגדר נכון קובץ network.
        /// </summary>
        internal static string NetworkIsNotDefined {
            get {
                return ResourceManager.GetString("NetworkIsNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תחנה חדשה.
        /// </summary>
        internal static string NewStation {
            get {
                return ResourceManager.GetString("NewStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רשימת הצמתים ריקה.
        /// </summary>
        internal static string NodeListIsNull {
            get {
                return ResourceManager.GetString("NodeListIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא נמצאו תחנות איזורי מחיר שמכילים תחנות.
        /// </summary>
        internal static string NonStationToExportToZonePriceArea {
            get {
                return ResourceManager.GetString("NonStationToExportToZonePriceArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רשימת הקווים ריקה.
        /// </summary>
        internal static string NonUpdatedList {
            get {
                return ResourceManager.GetString("NonUpdatedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא כל השכבות קיימות.
        /// </summary>
        internal static string NotAllLayersExists {
            get {
                return ResourceManager.GetString("NotAllLayersExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הפעולה בוטלה על-ידי המשתמש.
        /// </summary>
        internal static string OperationCanceledByUser {
            get {
                return ResourceManager.GetString("OperationCanceledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אשכול מספר {0} שרשום בקובץ הגדרות של מפעיל לא נמצא בבסיס הנתונים.
        /// </summary>
        internal static string OperatorHasClusterIdInXMLThatNotFoundInDB {
            get {
                return ResourceManager.GetString("OperatorHasClusterIdInXMLThatNotFoundInDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא מוגדר work space ספריה עבור מפעיל.
        /// </summary>
        internal static string OperatorWorkSpaceNotDefined {
            get {
                return ResourceManager.GetString("OperatorWorkSpaceNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שכבת תחנות פיזיות מכילה תחנות עם מקט שמתחילות ב6 וערך גדול מי 65535.
        /// </summary>
        internal static string PhisicalStopsCatalogMore65535 {
            get {
                return ResourceManager.GetString("PhisicalStopsCatalogMore65535", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שכבת תחנות פיזיות מכילה תחנות שלא נמצאים בשום פוליגון של שכבה מוניסיפאלית.
        /// </summary>
        internal static string PhisicalStopsCatalogNoHaveIsMun {
            get {
                return ResourceManager.GetString("PhisicalStopsCatalogNoHaveIsMun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ישנן תחנות שלא מקושרות לשום אזור מחיר.
        /// </summary>
        internal static string PhisicalStopsNoneAreaPrice {
            get {
                return ResourceManager.GetString("PhisicalStopsNoneAreaPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פעולת עדכון של אזור מחיר נכשלה.
        /// </summary>
        internal static string PriceListUpdateFailed {
            get {
                return ResourceManager.GetString("PriceListUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ישנם איזורים שעבורם לא הוגדרו שם או קוד.
        /// </summary>
        internal static string PriceListWithEmptyCodeOrDesc {
            get {
                return ResourceManager.GetString("PriceListWithEmptyCodeOrDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תיאור דרך.
        /// </summary>
        internal static string RoadDescription {
            get {
                return ResourceManager.GetString("RoadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם קו.
        /// </summary>
        internal static string Route_Name {
            get {
                return ResourceManager.GetString("Route_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן להמשיך בתהליך כי לא נבחרו קוים.
        /// </summary>
        internal static string RouteExportListIsEmpty {
            get {
                return ResourceManager.GetString("RouteExportListIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רשימת הקוים ריקה.
        /// </summary>
        internal static string RouteLineIsEmpty {
            get {
                return ResourceManager.GetString("RouteLineIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שים לב, לחלק מהקווים עדין לא נקבע תאריך תחילת פעילות, קווים אלו לא יועברו לרישוי.
        /// </summary>
        internal static string RouteLineNotValidExportDate {
            get {
                return ResourceManager.GetString("RouteLineNotValidExportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לקו {0} באשכול {1} עדין לא נקבע תאריך תחילת פעילות, קו זה לא יועבר לרישוי.
        /// </summary>
        internal static string RouteLineOneNotValidExportDate {
            get {
                return ResourceManager.GetString("RouteLineOneNotValidExportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר קו.
        /// </summary>
        internal static string RouteNumber {
            get {
                return ResourceManager.GetString("RouteNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תחנה ראשונה בקו לא תחנת עליה.
        /// </summary>
        internal static string RouteStopsFirstStationNotEmbarkation {
            get {
                return ResourceManager.GetString("RouteStopsFirstStationNotEmbarkation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תחנה אחרונה בקו לא תחנת הורדה.
        /// </summary>
        internal static string RouteStopsLastStationNotLanding {
            get {
                return ResourceManager.GetString("RouteStopsLastStationNotLanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מרחק בין שני תחנות מספר {0} ן {1} שווה 0.
        /// </summary>
        internal static string RouteStopsLastTwoStationEqualDistance {
            get {
                return ResourceManager.GetString("RouteStopsLastTwoStationEqualDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קו תחנה לא מוגדר לקו.
        /// </summary>
        internal static string RouteStopsLessThen2 {
            get {
                return ResourceManager.GetString("RouteStopsLessThen2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} נתיב לקובץ קוים של טרנסקדשגוי.
        /// </summary>
        internal static string RouteSystemFileWrong {
            get {
                return ResourceManager.GetString("RouteSystemFileWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר ספריה שבה יווצרו קבצי שייפ וטאב של שכבת הרחובות.
        /// </summary>
        internal static string SelectShapeFileToTabFolder {
            get {
                return ResourceManager.GetString("SelectShapeFileToTabFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שילוט.
        /// </summary>
        internal static string Signpost {
            get {
                return ResourceManager.GetString("Signpost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לאחר הזזת התחנה למיקום החדש, ישתנה אזור המחיר.
        /// </summary>
        internal static string StationAreaProceWillBeChanged {
            get {
                return ResourceManager.GetString("StationAreaProceWillBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שים לב, התחנה תתבטל והקווים יעברו לתחנה {0} שנמצאת באזור {1}.
        /// </summary>
        internal static string StationCanceledWillMovedToNewArea {
            get {
                return ResourceManager.GetString("StationCanceledWillMovedToNewArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שים לב, התחנה תתבטל והקווים יעברו לתחנה &apos;%%%%%&apos; שלא נמצאת באזור  מחיר.
        /// </summary>
        internal static string StationCanceledWillMovedToNonArea {
            get {
                return ResourceManager.GetString("StationCanceledWillMovedToNonArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to במיקום תחנה הקיים למפעיל אין איזור מחיר.
        /// </summary>
        internal static string StationDoesnotHasCurrentAreaPrice {
            get {
                return ResourceManager.GetString("StationDoesnotHasCurrentAreaPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to במיקום תחנה החדש למפעיל אין איזור מחיר.
        /// </summary>
        internal static string StationDoesnotHasNewAreaPrice {
            get {
                return ResourceManager.GetString("StationDoesnotHasNewAreaPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שים לב, התחנה אינה משוייכת לאזור מחיר.
        /// </summary>
        internal static string StationDoesnotHasNewAreaPriceAndOldPriceArea {
            get {
                return ResourceManager.GetString("StationDoesnotHasNewAreaPriceAndOldPriceArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רשימת התחנות ריקה.
        /// </summary>
        internal static string StationListIsNull {
            get {
                return ResourceManager.GetString("StationListIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא הוגדרו תחנות בקובץ קלט.
        /// </summary>
        internal static string StationNotDefinedInImportFile {
            get {
                return ResourceManager.GetString("StationNotDefinedInImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to למפעיל {0} לא הוגדר אף אשכול בבסיס הנתונים.
        /// </summary>
        internal static string TheOperDoesntHaveClusters {
            get {
                return ResourceManager.GetString("TheOperDoesntHaveClusters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אפליקצית טראנסכד כבר רצה, נא סגור אותה ונסה שנית.
        /// </summary>
        internal static string TranscadAlreadyRun {
            get {
                return ResourceManager.GetString("TranscadAlreadyRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא נמצאו נתונים של קוים בטראנסכד.
        /// </summary>
        internal static string TranscadLinelDBListEmpty {
            get {
                return ResourceManager.GetString("TranscadLinelDBListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא קיימים נתונים של נספח 3 בטראנסכד.
        /// </summary>
        internal static string TranscadNispah3DBListEmpty {
            get {
                return ResourceManager.GetString("TranscadNispah3DBListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא נמצאו נתונים של תחנות בטראנסכד.
        /// </summary>
        internal static string TranscadPhysicalDBListEmpty {
            get {
                return ResourceManager.GetString("TranscadPhysicalDBListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אפליקצית קליטה לא הוגדרה נכון.
        /// </summary>
        internal static string TvunaApplicationFileWasNotFound {
            get {
                return ResourceManager.GetString("TvunaApplicationFileWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שגיאה בתוכנית של הגדרת תהליך היצצוא.
        /// </summary>
        internal static string UnSuccesefullInputExport {
            get {
                return ResourceManager.GetString("UnSuccesefullInputExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המשתמש לא שייך לאפליקציה.
        /// </summary>
        internal static string UserDoesntBelongToGroup {
            get {
                return ResourceManager.GetString("UserDoesntBelongToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן להפעיל קובץ {0} כי הוא נעול על ידי משתמש {1}, נסה מאוחר יותר..
        /// </summary>
        internal static string WorSpaceAlreadyOccupiedByOtherUser {
            get {
                return ResourceManager.GetString("WorSpaceAlreadyOccupiedByOtherUser", resourceCulture);
            }
        }
    }
}
